# Basic Info
name: CMDR Leakspin
description: A Distant Worlds 2 Gallery
url: https://dw2.adrianmora.me

# Socials
twitter: CMDRLeakspin
github: amg1893

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jemoji
  - jekyll-admin