# Basic Info
name: CMDR Leakspin
title: CMDR Leakspin - A Distant Worlds 2 Gallery
bio: Leakspin has decided to create a gallery for his Distant Worlds 2 expedition.
description: A Distant Worlds 2 Gallery
url: https://dw2.adrianmora.me
logo: /images/favicon/favicon-196x196.png

analytics-google: UA-108062404-3

# Socials
twitter:
  username: CMDRLeakspin
  card: summary
twitch: leakspin
github: amg1893
inara: https://inara.cz/cmdr/142604/
coriolis: https://coriolis.io/outfit/asp?code=A0pfthFflidisnf5------0e0202023cv40i02409s2i.Iw18WQ%3D%3D.Aw18WQ%3D%3D.H4sIAAAAAAAAA2P8Z8%2FAwPCXEUhwfAGS%2FDz%2F%2Fv8X28DCwPCf%2BZ8USIoVSPypABL8Kr%2F%2B%2Fxfawc3AIFIjysAgcQco8%2F8%2FAwMAdE4sIkMAAAA%3D.EweloBhBmUA4QFMCGBzANokICMF8hRFA&bn=Nanotyrannus

social:
  name: CMDR Leakspin
  links:
    - https://twitter.com/CMDRLeakspin
    - https://github.com/amg1893

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jemoji
  - jekyll-admin